### ISSUE TITLE
Casting error in VCFparser.java

### ISSUE THREAD

**Issue by wiedenhoeft** [bioinform/varsim#110] opened 2017-04-03 17:08 UTC
I've tried to run (a fixed version of) quickstart.sh. However, I get the following fatal error:

03 Apr 2017 13:01:15,612  INFO [main] (SimpleReference.java:62): Read ref: hs37d5:hs37d5
03 Apr 2017 13:01:15,674  INFO [main] (VCFparser.java:45): Reading /u2/home/wiedenhoeft/software/varsim/All.vcf.gz
03 Apr 2017 13:01:15,693 FATAL [main] (VCFparser.java:662): Cannot cast java.lang.Boolean to [Ljava.lang.String;
1	10019	rs775809821	TA	T	.	.	RS=775809821;RSPOS=10020;dbSNPBuildID=144;SSR=0;SAO=0;VP=0x050000020005000002000200;GENEINFO=DDX11L1:100287102;WGT=1;VC=DIV;R5;ASP
java.lang.ClassCastException: Cannot cast java.lang.Boolean to [Ljava.lang.String;
	at java.lang.Class.cast(Class.java:3369)
	at com.bina.varsim.types.VCFInfo$VCFInfoElement.<init>(VCFInfo.java:75)
	at com.bina.varsim.types.VCFInfo.<init>(VCFInfo.java:30)
	at com.bina.varsim.util.VCFparser.processLine(VCFparser.java:309)
	at com.bina.varsim.util.VCFparser.parseLine(VCFparser.java:659)
	at com.bina.varsim.tools.simulation.RandVCF2VCF.countVariants(RandVCF2VCF.java:102)
	at com.bina.varsim.tools.simulation.RandVCF2VCF.run(RandVCF2VCF.java:281)
	at com.bina.varsim.VarSim.runVarSimTool(VarSim.java:62)
	at com.bina.varsim.VarSim.run(VarSim.java:112)
	at com.bina.varsim.VarSim.main(VarSim.java:30)

**Comment by yunfeiguo** [comment] 2017-04-11 01:41
Hi,

What version of VarSim are you using? Thanks.

**Comment by wiedenhoeft** [comment] 2017-04-13 19:22
I'm using 0.4.1.

**Comment by marghoob** [comment] 2017-04-25 18:05
@wiedenhoeft did you check against the latest version of VarSim 0.7.8?

**Comment by iranmdl** [comment] 2017-06-19 14:32
I'm having the same error. VarSim 0.7.1

`19 Jun 2017 16:30:37,602 FATAL [main] (VCFparser.java:662): Cannot cast java.lang.Boolean to [Ljava.lang.String;`

Any solution?

**Comment by yunfeiguo** [comment] 2017-06-19 15:02
Could you try latest version? The issue has been fixed. Thanks.

**Comment by iranmdl** [comment] 2017-06-19 16:23
Yes sorry! fixed :)
However...now I'm getting another error...:

`tail log/RandDGV2VCF.err`


```
19 Jun 2017 18:01:07,205  WARN [main] (DGVparser.java:214): Unrecognized subtype: gain+loss
19 Jun 2017 18:01:07,205  WARN [main] (DGVparser.java:215): line: esv16388	1	13607202	13645036	CNV	Gain+Loss	Conrad et al 2009	19812545	Composite_approach,Oligo_aCGH	Sanger H. Sapiens NimbleGen 42M CGH Array	esv29915	essv77763,essv42945,essv55328,essv58085,essv50743,essv32294,essv57750,essv83296,essv72016,essv65958,essv37807,essv73992,essv39373,essv44573,essv56509,essv34522,essv53542,essv76986,essv60218	M	451	18	1		PRAMEF15,PRAMEF7,PRAMEF8,PRAMEF9	NA06985,NA11931,NA11993,NA12156,NA12287,NA12489,NA12776,NA18502,NA18508,NA18511,NA18523,NA18909,NA19099,NA19108,NA19147,NA19190,NA19225,NA19240,NA19257
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.bina.varsim.tools.simulation.RandVCFgenerator.fillInSeq(RandVCFgenerator.java:123)
	at com.bina.varsim.tools.simulation.RandDGV2VCF.randOutputVcfRecord(RandDGV2VCF.java:262)
	at com.bina.varsim.tools.simulation.RandDGV2VCF.sampleFromDGV(RandDGV2VCF.java:210)
	at com.bina.varsim.tools.simulation.RandDGV2VCF.run(RandDGV2VCF.java:291)
	at com.bina.varsim.VarSim.runVarSimTool(VarSim.java:65)
	at com.bina.varsim.VarSim.run(VarSim.java:112)
	at com.bina.varsim.VarSim.main(VarSim.java:30)
```

**Comment by iranmdl** [comment] 2017-06-26 13:17
Any help on this, please?

**Comment by yunfeiguo** [comment] 2017-06-26 16:28
Sure. Let me take a look.

**Comment by yunfeiguo** [comment] 2017-06-26 19:38
Hi @iranmdl 

So the error is probably caused by very short insert length of `insert_seq.txt` or by very large insertion that needs to be filled by VarSim. Could you check the following  after entering your execution directory?

1. ` grep -A 10 randdgv2vcf log/varsim.log`
2. `wc insert_seq.txt`

if both are fine, we can look at other things. Thanks.

**Comment by iranmdl** [comment] 2017-06-28 11:18
Ok, I manage to fix the issue I'm not sure how. However.. another error popped out:

`art_command is not found or something similar`

I looked into `varsim.py` script and:

```
elif simulator == "art":
            for i in xrange(nlanes):
                simulator_command = "{} {} -i {} -f {} -rs {} -o {}".format(simulator_exe, simulator_options, merged_reference, coverage_per_lane, seed + i, os.path.join(out_dir, "simulated.lane%d.read" % (i)))
                simulator_commands_files.append((art_command, os.path.join(log_dir, "art.lane%d.out" % (i)), os.path.join(log_dir, "art.lane%d.err" % (i))))
```
I replaced `art_command` with `simulator_command` and everything works nice now. Looking the code it will happen the same if `dwgsim` is chosen as simulator tool.

:)

**Comment by marghoob** [comment] 2018-01-09 01:23
Fixed in the most recent version of varsim.

**Closed by marghoob** 2018-01-09 01:23 UTC
